[project]
name = "aquabuoy-code"
version = "0.0.1"
description = "Python port of the original MATLAB code for the Aquabuoy project"

[build-system]

requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["aquabuoy"]

